name = "reel-revision"
compatibility_date = "2025-05-31"
main = "src/worker.ts"

[site]
bucket = "./dist"
include = ["dist/**/*"]

[build]
command = "npm run build"

[env.production]
vars = { ENVIRONMENT = "production" } 